Model:
    CharSet: [' ', '2', '1', '7', '3', '4', '6', '5', '8', '9', '0']
    ImageChannel: 3
    ImageHeight: 64
    ImageWidth: -1
    Word: false
System:
    Allow_Ext: [jpg, jpeg, png, bmp]
    GPU: true
    GPU_ID: 0
    Path: ./images/
    Project: AutoRunMap
    Val: 0.03
Train:
    BATCH_SIZE: 32
    CNN: {NAME: ddddocr}
    DROPOUT: 0.3
    LR: 0.01
    OPTIMIZER: SGD
    SAVE_CHECKPOINTS_STEP: 2000
    TARGET: {Accuracy: 0.99, Cost: 0.01, Epoch: 20}
    TEST_BATCH_SIZE: 32
    TEST_STEP: 1000
